// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl72ojCl9uXLiQpsHI1qc8SIxfPohl9y8',
    appId: '1:957758662265:web:8d255c05c2ceecb4d216a8',
    messagingSenderId: '957758662265',
    projectId: 'notificacionesflutter-c1be9',
    authDomain: 'notificacionesflutter-c1be9.firebaseapp.com',
    storageBucket: 'notificacionesflutter-c1be9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX_OBv6Q1njSHTPiC0ZBFmz7mDQKg1ZP0',
    appId: '1:957758662265:android:0ffeb5f46d5c1fd0d216a8',
    messagingSenderId: '957758662265',
    projectId: 'notificacionesflutter-c1be9',
    storageBucket: 'notificacionesflutter-c1be9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gjKI3yOPqjbwAmfVt0PZtrtSHnnFAeA',
    appId: '1:957758662265:ios:01df30437df11b6ad216a8',
    messagingSenderId: '957758662265',
    projectId: 'notificacionesflutter-c1be9',
    storageBucket: 'notificacionesflutter-c1be9.appspot.com',
    iosClientId: '957758662265-pue9ruakkqinvh0spk70ujehl43l5voc.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificacionesmovulysmartwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4gjKI3yOPqjbwAmfVt0PZtrtSHnnFAeA',
    appId: '1:957758662265:ios:b501914e52bb62fad216a8',
    messagingSenderId: '957758662265',
    projectId: 'notificacionesflutter-c1be9',
    storageBucket: 'notificacionesflutter-c1be9.appspot.com',
    iosClientId: '957758662265-a9gg9ml8cu6754b8d3saiuukmgmop85o.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificacionesmovulysmartwatch.RunnerTests',
  );
}
